### ISSUE TITLE
Why no Context.GlobalGlobalBoolT

### ISSUE THREAD

**Issue by LukeMauldin** [codegangsta/cli#206]
All of the other Context.X methods have a Context.GlobalX matching method.  Why not for BoolT?

**Comment by apriendeau** [comment]
Context.BoolT is there but underneath the hood, if you look at the functions, they are the same. So really with any Context reader, I would use Context.Bool because in the end they are both booleans and just inverse defaults when being set. BoolT is more helpful when setting the values. 

I agree consistency is a good thing but I would argue for removing BoolT before adding GlobalBoolT.

Here is the code that I am referencing: https://github.com/codegangsta/cli/blob/master/context.go#L279

**Comment by jszwedko** [comment]
Yeah, I'm not a big fan of `BoolT` -- I feel like we should be able to get the same effect by just adding `.Value` to the `Bool` Flag and users can default the flag to `true`.

But you are correct that we should have a `GlobalBoolT` for now since I'd prefer not to break the API.
