### ISSUE TITLE
CommandNotFound if app.Action is set

### ISSUE THREAD

**Issue by Mau04** [codegangsta/cli#354]
I'm trying to achieve the following:

mycommand
-> execute app.Action

mycommand validsubcommand
-> execute subcommand

mycommand invalidsubcommand
-> print help

CommandNotFound does not do anything in this case.

How can I catch invalid subcommands? Right now, app.Action is executed on an invalid subcommand.

**Comment by jszwedko** [comment]
Hi @Mau04,

It does appear that `CommandNotFound` is only executed in cases where there is no `app.Action`. I imagine this is because it isn't currently possible to determine if it was actually an invalid subcommand or if `app.Action` just happens to takes arguments. In your situation, since you know that you don't want `app.Action` to take arguments I'd recommend checking `len(context.Args())` and calling `ShowCommandHelp` directly if there are any.

**Comment by Mau04** [comment]
This is how I did it:

```
app.Action = func(c *cli.Context) {
    if (len(c.Args()) > 0) {
      fmt.Printf("'%s' is not a valid command.", c.Args().First())
      cli.ShowAppHelp(c)
    } else {
      //execute app action
    }
}
```
